== Configuration

:icons: font

This is the default configuration of the application +
It sets the server port to 8080 and the knowledgebase-directory to `build/knowledgebase`

[source,yaml]
----
include::../../configuration.yml[]
----

=== Server port
The default port of this application is `8080`
So if you want to access the webUI on your local machine navigate to `https://localhost:8080`.If you want to change that port, see <<_via_command_line_arguments, Changing via command line arguments>>

=== Knowledgebase
This entry means, that there has to be a folder named `build/knowlegebase` beside your jar file. You can specify which
knowledgebase to use, by changing it via the command line arguments (How that works will be covered by me
a https://github.com/Cuupa/classificator#Changing-the-configuration[few lines down below]).

TIP: If this entry only contains a folder name without the specific knowlegedbase, it will load the file with the highest version tag in that folder +
For example if you have `kb-1.0.0.db` and `kb-1.0.1.db` it'll load the `kb-1.0.1.db`
[source,yaml]
----
knowlegde_base: build/knowledgebase

----

=== Monitor
The monitor is enabled by default and uses the database `monitor.db`
[source,yaml]
----
 monitor:
    username: "John"
    password: "Doe"
    enabled: true
    logText: true
    database_name: "monitor.db"

----

==== Username and password
These entries set the username and password for accessing the statistics under `/monitor`

==== Database name
The database name is defined via `database_name`. You can change it to your likings. It uses relative paths by default. If you want to use absolute paths, change it to
[source,yaml]
----
database_name: "C:\Users\John Doe\monitor.db"
----
==== Enabled and logText
If `enabled` is set to `true`, all events will be logged. To turn it off, set it to `false`.
If `logText` is enabled, the actual analyzed texts will be logged into the database. You might want to turn it off for privacy reasons, but it really helps finding errors in the classification process.

=== Changing

CAUTION: If you use the command line arguments, the corresponding entry in the configuration.yml will be overwritten

==== Via config
If you want to change the configuration, just edit it with any text editor and change it to your likings
[source,yaml]
----
knowlegde_base: knowledgebase/kb-1.0.0.db
----

or

[source,yaml]
----
monitor:
  logText: false
----

Save the file and restart your application.

NOTE: Changing the config file and restarting the application is the recommended way of changing program parameters.

==== Via command line arguments
You can also use the command line arguments

CAUTION: The server port can only be changed by using the command line arguments

[source,shell]
----
java -jar app.jar '--server_port=8080' '--knowledge_base=knowlegebase/kb-1.0.0.db' '--classificator.monitor.logText=false' '--configuration=/opt/classificator/configuration.yml'
----

NOTE: The first part simply runs the jar by the name "app.jar" +
[source,shell]
----
java -jar app.jar
----

NOTE: This part sets the port to 8080 and overwrites the value of the default configuration
[source,shell]
----
--server_port=8080
----

NOTE: This part sets the location of the knowledgebase. You can use relative paths like
[source,shell]
----
--knowledge_base=knowlegebase/kb-1.0.0.db
----

NOTE: or absolute paths like
[source,shell]
----
--knowledge_base="C:\Users\John Doe\knowlegebase\kb-1.0.0.db"
----
CAUTION: If your parameter contains a whitespace (eg a `blank`) you need to quote the value

[source, shell]
----
--configuration=/opt/classificator/configuration.yml
----
NOTE: Sets the path to the configuration file
