---
classificator:
  knowledge_base: build/knowledgebase
  api_key_required: true

  admin:
    username: "Jane"
    password: "Doe"

  monitor:
    username: "John"
    password: "Doe"
    enabled: true
    logText: true
    database_name: "monitor.db"