---
classificator:
  knowledge_base: build/knowledgebase

  api_key_required: true

  admin:
    username: "admin"
    password: "admin"

  monitor:
    username: "admin"
    password: "admin"
    enabled: true
    logText: true
    database_name: "monitor.db"

  trainer:
    database_name: "trainer.db"