server_port: 8080

server:
  port: ${server_port}

logging.level:
  root: ERROR
  com.cuupa.classificator: DEBUG

classificator.kbfiles: ${knowlegde_base}


  monitor:
    enabled: true
    logText: true
    fileeventstorage.path: /home/simon/IdeaProjects/classificator/