server_port: 8080
knowlegde_base:

server.port: ${server_port}

logging.level:
  root: ERROR
  com.cuupa.classificator: WARN

classificator:
  kbfiles: ${knowlegde_base}

  monitor:
    username:
    password:
    enabled:
    logText:
    database-name: