server_port: 8080
knowlegde_base: build/knowledgebase
monitor_path: build/monitor

server.port: ${server_port}

logging.level:
  root: ERROR
  com.cuupa.classificator: DEBUG

classificator:
  kbfiles: ${knowlegde_base}

  monitor:
    enabled: true
    logText: true
    fileeventstorage.path: ${monitor_path}