server_port: 8080

server:
  port: ${server_port}

logging.level:
  root: ERROR
  com.cuupa.classificator: DEBUG

classificator:
  kbfiles: classpath:kbfiles
  metadatafiles: classpath:kbfiles/metadata
  regexfiles: classpath:kbfiles/regex
  senderFiles: classpath:kbfiles/senders
