server_port: 8080
knowlegde_base:

server.port: ${server_port}

springdoc:
  api-docs.path: /api/api-docs
  swagger-ui.path: /api/swagger-ui

logging.level:
  root: ERROR
  com.cuupa.classificator: debug

classificator:
  kbfiles: ${knowlegde_base}

  admin:
    username: admin
    password: admin

  monitor:
    username:
    password:
    enabled:
    logText:
    database_name:

  api_repository:
    database_name: "api_repository.db"
