server_port: 8080
knowlegde_base:

server.port: ${server_port}

springdoc:
  api-docs.path: /api/api-docs
  swagger-ui.path: /api/swagger-ui

logging.level:
  root: ERROR
  com.cuupa.classificator: DEBUG

classificator:
  kbfiles: ${knowlegde_base}

  monitor:
    username:
    password:
    enabled:
    logText:
    database-name: